POST http://localhost:8083/order-service/orders
Content-Type: application/json

{
  "purchaseProductDTOS": [
    {
      "productId": 1,
      "quantity": 2,
      "price": 29.99
    },
    {
      "productId": 2,
      "quantity": 1,
      "price": 59.49
    }
  ],
  "city": "London"
}